site_name: Cours complet de Trictrac
site_author: Henri Bourcereau
site_url: https://mmai.github.io/coursCompletDeTrictrac/

# repository
repo_url: https://github.com/mmai/coursCompletDeTrictrac/
repo_name: code source
edit_uri: "" # disable edit button linking to repository

# files paths
docs_dir: src/
site_dir: html/

nav:
  - Présentation: index.md
  - Discours préliminaire: discoursPreliminaire.md
  - Première partie: premierePartie.md
  - Deuxième partie: deuxiemePartie.md
  - Troisième partie: troisiemePartie.md
  - Quatrième partie: quatriemePartie.md
  - Appendix: appendix.md

markdown_extensions:
  - pm_attr_list

# -----  Config for Material theme ------
# theme:
#   name: material
#   language: fr
#   features:
#     # - announce.dismiss
#     # - content.code.annotate
#     # - content.tabs.link
#     - content.tooltips
#     # - header.autohide
#     # - navigation.expand
#     - navigation.indexes
#     # - navigation.instant
#     # - navigation.prune
#     - navigation.sections
#     # - navigation.tabs
#     # - navigation.tabs.sticky
#     - navigation.top
#     - navigation.tracking
#     - search.highlight
#     - search.share
#     - search.suggest
#     - toc.follow
#     # - toc.integrate
#
#   # analytics:
#   #   gtag: G-7P8EEWM1YZ
# extra:
#   # analytics:
#   #   provider: google
#   #   property: G-B6PEG20J74
#   social:
#       - icon: fontawesome/brands/github
#         link: https://github.com/mmai
#       - icon: fontawesome/brands/mastodon
#         link: https://mamot.fr/@mmai
# ----- Config for Readthedoc theme ------
theme:
  name: readthedocs
  analytics:
    gtag: G-B6PEG20J74
