site_name: Traité complet de Trictrac
site_author: Henri Bourcereau
site_url: https://mmai.github.io/traiteCompletTrictrac/

# repository
repo_url: https://github.com/mmai/traiteCompletTrictrac/
repo_name: code source
edit_uri: "" # disable edit button linking to repository

# files paths
docs_dir: src/
site_dir: html/

nav:
  - Présentation: index.md
  - Avertissement: avertissement.md
  - Introduction: introduction.md
  - Chapitre I: chapitre1.md
  - Chapitre II: chapitre2.md
  - Chapitre III: chapitre3.md
  - Chapitre IV: chapitre4.md
  - Chapitre V: chapitre5.md
  - Chapitre VI: chapitre6.md
  - Chapitre VII: chapitre7.md
  - Chapitre VIII: chapitre8.md
  - Chapitre IX: chapitre9.md
  - Chapitre X: chapitre10.md
  - Chapitre XI: chapitre11.md
  - Chapitre XII: chapitre12.md
  - Chapitre XIII: chapitre13.md
  - Chapitre XIV: chapitre14.md
  - Chapitre XV: chapitre15.md
  - Le trictrac comparé: le-trictrac-compare.md
  - Traité du jeu de Backgammon: traite-du-jeu-de-backgammon.md

markdown_extensions:
  - footnotes
  # - material-plausible
  # - pm_attr_list

# -----  Config for Material theme ------
theme:
  name: material
  custom_dir: overrides
  language: fr
  features:
    # - announce.dismiss
    # - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra:
  analytics:
    provider: plausible
    domain: mmai.github.io
    src: "https://webstats.rhumbs.fr/js/touch.js"
  social:
      - icon: fontawesome/brands/github
        link: https://github.com/mmai
      - icon: fontawesome/brands/mastodon
        link: https://social.rhumbs.fr/@mmai
# ----- Config for Readthedoc theme ------
# theme:
#   name: readthedocs
  # analytics:
  #   gtag: G-B6PEG20J74
