site_name: Traité complet de Trictrac
site_author: Henri Bourcereau
site_url: https://mmai.github.io/traiteCompletTrictrac/

# repository
repo_url: https://github.com/mmai/traiteCompletTrictrac/
repo_name: code source
edit_uri: "" # disable edit button linking to repository

# files paths
docs_dir: src/
site_dir: html/

nav:
  - Introduction: introduction.md
  - Chapitre I: chapitre1.md
  - Chapitre II: chapitre2.md
  - Chapitre III: chapitre3.md
  - Chapitre IV: chapitre4.md
  - Chapitre V: chapitre5.md
  - Chapitre VI: chapitre6.md
  - Chapitre VII: chapitre7.md
  - Chapitre VIII: chapitre8.md
  - todo: guiton.md

markdown_extensions:
  - footnotes
  # - pm_attr_list

# -----  Config for Material theme ------
# theme:
#   name: material
#   language: fr
#   features:
#     # - announce.dismiss
#     # - content.code.annotate
#     # - content.tabs.link
#     - content.tooltips
#     # - header.autohide
#     # - navigation.expand
#     - navigation.indexes
#     # - navigation.instant
#     # - navigation.prune
#     - navigation.sections
#     # - navigation.tabs
#     # - navigation.tabs.sticky
#     - navigation.top
#     - navigation.tracking
#     - search.highlight
#     - search.share
#     - search.suggest
#     - toc.follow
#     # - toc.integrate
#
#   # analytics:
#   #   gtag: G-7P8EEWM1YZ
# extra:
#   # analytics:
#   #   provider: google
#   #   property: G-B6PEG20J74
#   social:
#       - icon: fontawesome/brands/github
#         link: https://github.com/mmai
#       - icon: fontawesome/brands/mastodon
#         link: https://mamot.fr/@mmai
# ----- Config for Readthedoc theme ------
theme:
  name: readthedocs
  analytics:
    gtag: G-B6PEG20J74
